package model;

/**
 * 📦 Student — a POJO (Plain Old Java Object).
 *
 * Each field maps to a column in the `students` table:
 *   id    → INT PRIMARY KEY AUTO_INCREMENT
 *   name  → VARCHAR(100)
 *   email → VARCHAR(150) UNIQUE
 *   age   → INT
 */
public class Student {

    private int    id;
    private String name;
    private String email;
    private int    age;

    // ── Constructors ────────────────────────────────────────

    /** Used when READING from DB (id is known) */
    public Student(int id, String name, String email, int age) {
        this.id    = id;
        this.name  = name;
        this.email = email;
        this.age   = age;
    }

    /** Used when INSERTING (id is auto-generated by DB) */
    public Student(String name, String email, int age) {
        this.name  = name;
        this.email = email;
        this.age   = age;
    }

    // ── Getters ─────────────────────────────────────────────
    public int    getId()    { return id;    }
    public String getName()  { return name;  }
    public String getEmail() { return email; }
    public int    getAge()   { return age;   }

    // ── Setters ─────────────────────────────────────────────
    public void setId(int id)        { this.id = id;       }
    public void setName(String name) { this.name = name;   }
    public void setEmail(String email){ this.email = email; }
    public void setAge(int age)      { this.age = age;     }

    // ── toString (for printing) ─────────────────────────────
    @Override
    public String toString() {
        return "Student { id=" + id
             + ", name='" + name + '\''
             + ", email='" + email + '\''
             + ", age=" + age + " }";
    }
}